server.port=8080
server.servlet.context-path=/digit-assignment

spring.datasource.url=jdbc:postgresql://localhost:5432/digit_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/main
spring.flyway.baseline-on-migrate=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=advocate-group
spring.kafka.consumer.auto-offset-reset=earliest

egov.idgen.host=http://localhost:8285
egov.idgen.path=/egov-idgen/id/_generate
egov.mdms.host=http://localhost:8094
egov.mdms.search.endpoint=/mdms-v2/v2/_search
egov.workflow.host=http://localhost:8280
egov.workflow.transition.path=/egov-workflow-v2/egov-wf/process/_transition
egov.workflow.businessservice.search.path=/egov-workflow-v2/egov-wf/businessservice/_search

kafka.topics.save.advocate=save-advocate
kafka.topics.update.advocate=update-advocate

egov.idgen.advocate.name=advocate.applicationNumber
egov.idgen.advocate.format=ADVOC-[SEQ_ADVOC_[TENANT_ID]]-[cy:yyyy]
egov.idgen.advocate.clerk.name=advocate.clerk.applicationNumber
egov.idgen.advocate.clerk.format=ADVOC-CLERK-[SEQ_ADVOC_CLERK_[TENANT_ID]]-[cy:yyyy]

egov.workflow.advocate.business.service=advocate-registration
egov.workflow.advocate.modulename=digit_assignment
